### PR TITLE
Add Screenshot to README.md

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

**Comment by aoloe** [comment]
looks good to me.

you could add a link to the mailing list archives to replace the one to the defunct mailing list:

https://www.mail-archive.com/undertype-users@gna.org/maillist.html

**Comment by probonopd** [comment]
That link is giving me SSL_ERROR_BAD_MAC_READ...

**Comment by aoloe** [comment]
works from here...

**Comment by probonopd** [comment]
Maybe it's something on my end, doesn't work today either...

**Pull request merged**
